// Generated by CoffeeScript 1.9.3
(function() {
  var i, sum, x;

  sum = 0;

  for (x = i = 1; i <= 999; x = ++i) {
    if (x % 3 === 0 || x % 5 === 0) {
      sum += x;
    }
  }

  console.log(sum);

}).call(this);
