#include <stdio.h>

/*
 * Berechnet die Loesung zu Problem 2 von Projekt Euler.
 * -----------------------------------------------------------------------------
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 * -----------------------------------------------------------------------------
 * Dies kann einfach ueber einen Brute-Force-Ansatz geloest werden. Wir
 * berechnen die Fibonaccizahlen kleiner gleich 4.000.000 und summieren alle
 * gerade Zahlen auf.
 * Wir haben hier nicht genutzt, dass genau jede dritte Fibonaccizahl gerade
 * ist (2. (2), 5. (8), 8. (34), 11. (144)...). Dies wuerde keinen
 * Geschwindigkeitsgewinn bringen.
 */
int solve() {
    int sum = 0;
    
    // Berechnung der Fibonaccizahlen kleiner gleich 4.000.000
    int i = 1;
    int j = 2;
    while (i <= 4000000) {
        
        // Aufsummieren der geraden Zahlen
        if (i % 2 == 0) {
            sum += i;
        }
        
        // Berechnung der naechsten Zahlen
        int k = i + j;
        i = j;
        j = k;
    }
    return sum;
}

int main() {
    int res = solve();
    printf("%i\n", res);
    return 0;
}
